FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
wget \
python3 \
python3-pip && \
rm -rf /var/lib/apt/lists/*

COPY search_word.sh word_finder.py config.txt /tmp/
RUN chmod +x /tmp/search_word.sh /tmp/word_finder.py

